apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-challenge

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - nextjs-deployment.yaml
  - nextjs-service.yaml
