apiVersion: v1
kind: Service
metadata:
  name: nextjs
  namespace: devops-challenge
spec:
  type: NodePort
  selector:
    app: nextjs
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
    name: http
