apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops-challenge
type: Opaque
data:
  # postgres
  POSTGRES_USER: cG9zdGdyZXM=
  # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # currencies
  POSTGRES_DB: Y3VycmVuY2llcw==
  # postgres://postgres:postgres@postgres:5432/currencies?schema=public
  POSTGRES_PRISMA_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlczo1NDMyL2N1cnJlbmNpZXM/c2NoZW1hPXB1YmxpYw==
